# Generated by Django 4.1.3 on 2023-09-21 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.CharField(default='d0171b7888', max_length=10, primary_key=True, serialize=False, verbose_name='File ID')),
                ('file_name', models.CharField(max_length=45, verbose_name='File name')),
                ('file_description', models.TextField(verbose_name='Description')),
                ('file_dir', models.CharField(max_length=255, verbose_name='File path')),
                ('file_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price')),
                ('file_pub_date', models.DateField(verbose_name='Date published')),
                ('file_status', models.CharField(choices=[('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('on_moderation', 'Moderation')], max_length=13, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='User ID')),
                ('username', models.CharField(default=None, max_length=32, verbose_name='@username')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=5, verbose_name='Role')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='USDT Balance')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Rating')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Wallet ID')),
                ('wallet_address', models.CharField(max_length=256, verbose_name='Wallet address')),
                ('wallet_currency', models.CharField(choices=[('tron', 'Tron'), ('usdt', 'USDT')], max_length=4, verbose_name='Wallet currency')),
                ('wallet_subnetwork', models.CharField(choices=[('trc_20', 'TRC-20')], max_length=6, verbose_name='Wallet subnetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.telegramuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Review ID')),
                ('review_message', models.TextField(verbose_name='Message')),
                ('review_rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='Rate')),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='Review date')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.file', verbose_name='File')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.telegramuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.telegramuser', verbose_name='Owner'),
        ),
    ]
