# Generated by Django 4.1.3 on 2023-11-22 09:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.CharField(default='a83d6ac68a', max_length=10, primary_key=True, serialize=False, verbose_name='File ID')),
                ('file_name', models.CharField(max_length=45, verbose_name='File name')),
                ('file_description', models.TextField(verbose_name='Description')),
                ('file_dir', models.CharField(max_length=255, verbose_name='File path')),
                ('file_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price')),
                ('file_pub_date', models.DateField(verbose_name='Date published')),
                ('file_status', models.CharField(choices=[('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('in_process', 'In process')], max_length=10, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'File',
                'verbose_name_plural': 'Files',
            },
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(unique=True, verbose_name='User ID')),
                ('username', models.CharField(default=None, max_length=32, verbose_name='@username')),
                ('role', models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=5, verbose_name='Role')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='USDT Balance')),
                ('rating', models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Rating')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('wallet_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Wallet ID')),
                ('wallet_address', models.CharField(max_length=256, verbose_name='Wallet address')),
                ('wallet_private_key', models.CharField(default='', max_length=256, verbose_name='Wallet private key')),
                ('wallet_currency', models.CharField(choices=[('tron', 'Tron'), ('usdt', 'USDT')], max_length=4, verbose_name='Wallet currency')),
                ('wallet_subnetwork', models.CharField(choices=[('trc_20', 'TRC-20')], max_length=6, verbose_name='Wallet subnetwork')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.telegramuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Transfer amount')),
                ('transaction_message', models.CharField(default='', max_length=25, verbose_name='Transaction message')),
                ('transaction_hash', models.CharField(max_length=256, verbose_name='Transaction hash')),
                ('transaction_status', models.CharField(choices=[('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('in_process', 'In process')], default='In process', max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Review ID')),
                ('review_message', models.TextField(verbose_name='Message')),
                ('review_rate', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1, verbose_name='Rate')),
                ('review_date', models.DateTimeField(auto_now_add=True, verbose_name='Review date')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.file', verbose_name='File')),
                ('owner_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.telegramuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order ID')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Order total amount')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Order date')),
                ('order_status', models.CharField(choices=[('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('in_process', 'In process')], max_length=10, verbose_name='Status')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.file', verbose_name='File')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.transaction', verbose_name='Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.telegramuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='file',
            name='owner_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.telegramuser', verbose_name='Owner'),
        ),
    ]
