# Generated by Django 4.1.3 on 2023-09-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(default='3288ae4d29', max_length=10, primary_key=True, serialize=False, verbose_name='File ID'),
        ),
    ]
