# Generated by Django 4.1.3 on 2023-09-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_alter_file_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(default='218121166e', max_length=10, primary_key=True, serialize=False, verbose_name='File ID'),
        ),
    ]
