# Generated by Django 4.1.3 on 2023-09-22 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0003_alter_file_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(default='a9a8e50de7', max_length=10, primary_key=True, serialize=False, verbose_name='File ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('in_process', 'In process')], max_length=10, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Transaction ID')),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Transfer amount')),
                ('transaction_hash', models.CharField(max_length=256, verbose_name='Transaction hash')),
                ('transaction_status', models.CharField(choices=[('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('in_process', 'In process')], max_length=10, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.wallet', verbose_name='Wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
            },
        ),
    ]
