# Generated by Django 4.1.3 on 2023-09-22 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_alter_file_file_id_alter_file_file_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_private_key',
            field=models.CharField(default=None, max_length=256, verbose_name='Wallet private key'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(default='994c767be5', max_length=10, primary_key=True, serialize=False, verbose_name='File ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transfer_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Transfer amount'),
        ),
    ]
