# Generated by Django 4.1.3 on 2023-09-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0005_wallet_wallet_private_key_alter_file_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(default='c8f6789a2b', max_length=10, primary_key=True, serialize=False, verbose_name='File ID'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='wallet_private_key',
            field=models.CharField(default='', max_length=256, verbose_name='Wallet private key'),
        ),
    ]
