# Generated by Django 4.1.3 on 2023-09-27 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_alter_file_file_id_alter_wallet_wallet_private_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(default='8283605540', max_length=10, primary_key=True, serialize=False, verbose_name='File ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='role',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], default='user', max_length=5, verbose_name='Role'),
        ),
    ]
