# Generated by Django 4.1.3 on 2023-09-27 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_alter_file_file_id_alter_telegramuser_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(default='c855f47802', max_length=10, primary_key=True, serialize=False, verbose_name='File ID'),
        ),
    ]
