# Generated by Django 4.1.3 on 2023-09-27 08:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0008_alter_file_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now, verbose_name='Created at'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(default='c1c69bf852', max_length=10, primary_key=True, serialize=False, verbose_name='File ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3, null=True, verbose_name='Rating'),
        ),
    ]
