# Generated by Django 4.1.3 on 2023-09-27 08:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0009_telegramuser_created_at_alter_file_file_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(default='2a8292ddc4', max_length=10, primary_key=True, serialize=False, verbose_name='File ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_created=True, default=datetime.datetime.now, null=True, verbose_name='Created at'),
        ),
    ]
