# Generated by Django 4.1.3 on 2023-10-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0011_alter_file_file_id_alter_telegramuser_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(default='e28fd5a10e', max_length=10, primary_key=True, serialize=False, verbose_name='File ID'),
        ),
    ]
