# Generated by Django 4.1.3 on 2023-10-01 08:29

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0012_alter_file_file_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(default='df961727dc', max_length=10, primary_key=True, serialize=False, verbose_name='File ID'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Order ID')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Order total amount')),
                ('order_date', models.DateTimeField(auto_now_add=True, verbose_name='Order date')),
                ('order_status', models.CharField(choices=[('canceled', 'Canceled'), ('confirmed', 'Confirmed'), ('in_process', 'In process')], max_length=10, verbose_name='Order date')),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.file', verbose_name='File')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.transaction', verbose_name='Transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketplace.telegramuser', verbose_name='User')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
