# Generated by Django 4.1.3 on 2023-10-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0014_transaction_transaction_message_alter_file_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='id',
            field=models.AutoField(default=0, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='file',
            name='file_id',
            field=models.CharField(default='92d5b0b182', max_length=10, primary_key=True, serialize=False, verbose_name='File ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='user_id',
            field=models.IntegerField(unique=True, verbose_name='User ID'),
        ),
    ]
